name: opentelemetry-demo-flagd
replicaCount: 1
revisionHistoryLimit: 10

instance: opentelemetry-demo
part-of: opentelemetry-demo
component: flagd

serviceAccount:
  name: opentelemetry-demo

flagd:
  name: flagd
  repository: ghcr.io/open-feature/flagd
  tag: v0.11.1
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 8013
    name: service
  resources:
    limits:
      memory: 75Mi

flagdui:
  name: flagdui
  repository: ghcr.io/open-telemetry/demo
  tag: 1.12.0-flagdui
  imagePullPolicy: IfNotPresent
  ports: 
     containerPort: 4000
     name: service
  resources:
    limits:
      memory: 75Mi


service:
  type: ClusterIP
  tcpService:
    port: 8013
    name: tcp-service
    targetPort: 8013
  tcpService0:
    port: 4000
    name: tcp-service-0
    targetPort: 4000
    


env:
  OTEL_SERVICE_NAME: flagd
  OTEL_COLLECTOR_NAME: opentelemetry-demo-otelcol
  FLAGD_METRICS_EXPORTER: otel
  FLAGD_OTEL_COLLECTOR_URI: $(OTEL_COLLECTOR_NAME):4317
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: cumulative
  OTEL_RESOURCE_ATTRIBUTES: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0



