apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/opentelemetry-demo-helm.git'
    targetRevision: HEAD
    path: '/'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ecom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true