apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentelemetry-demo-kafka.fullname" . }}
  labels:
    {{- include "opentelemetry-demo-kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "opentelemetry-demo-kafka.selectorLabels" . | nindent 4 }}
