apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "opentelemetry-demo-adservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opentelemetry-demo-adservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opentelemetry-demo-adservice.selectorLabels" . | nindent 8}}
    spec:
      serviceAccount: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.component }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
              name: {{ .Values.ports.name }}
          env:
           {{- range $key, $value := .Values.env }}
           - name: {{ $key }}
             value: {{ $value | quote }}
           {{- end }}
      initContainers:
        - command: "{{ .Values.initContainers.command }}"
          image: {{ .Values.initContainers.image }}
          name: {{ .Values.initContainers.name}}