name: opentelemetry-demo-productcatalogservice
replicaCount: 1
revisionHistoryLimit: 10

instance: opentelemetry-demo
part-of: opentelemetry-demo
component: productcatalogservice

serviceAccount:
  name: opentelemetry-demo

image :
  repository: abhishekf5/product-catalog
  tag: "13134113508"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  name: tcp-service
  targetPort: 8080

ports:
  containerPort: 8080
  name: service

resources:
  limits:
    memory: 20Mi

env:
  FLAG_HOST: opentelemetry-demo-flagd
  FLAG_PORT: 8013
  OTEL_SERVICE_NAME: productcatalogservice
  OTEL_COLLECTOR_NAME: opentelemetry-demo-otelcol
  PRODUCT_CATALOG_SERVICE_PORT: 8080
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: cumulative
  OTEL_EXPORTER_OTLP_ENDPOINT: http://$(OTEL_COLLECTOR_NAME):4317
  OTEL_RESOURCE_ATTRIBUTES: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0

