name: opentelemetry-demo-frontendproxy
replicaCount: 1
revisionHistoryLimit: 10

instance: opentelemetry-demo
part-of: opentelemetry-demo
component: frontendproxy

serviceAccount:
  name: opentelemetry-demo

image :
  repository: ghcr.io/open-telemetry/demo
  tag: "1.12.0-frontend"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  name: tcp-service
  targetPort: 8080

ports:
  containerPort: 8080
  name: service

resources:
  limits:
    memory: 250Mi

env:
  FLAGD_HOST: opentelemetry-demo-flagd
  FLAGD_PORT: 8013
  OTEL_SERVICE_NAME: frontendproxy
  OTEL_COLLECTOR_NAME: opentelemetry-demo-otelcol
  ENVOY_PORT: 8080
  FRONTEND_PORT: 8080
  FRONTEND_ADDR: :8080
  FLAGD_UI_HOST: opentelemetry-demo-flagd
  FLAGD_UI_PORT: 4000
  FRONTEND_HOST: opentelemetry-demo-frontend
  GRAFANA_SERVICE_HOST: opentelemetry-demo-grafana
  GRAFANA_SERVICE_PORT: 80
  IMAGE_PROVIDER_HOST: opentelemetry-demo-imageprovider
  IMAGE_PROVIDER_PORT: 8081
  JAEGER_SERVICE_HOST: opentelemetry-demo-jaeger-query
  JAEGER_SERVICE_PORT: 16686
  LOCUST_WEB_HOST: opentelemetry-demo-loadgenerator
  LOCUST_WEB_PORT: 8089
  OTEL_COLLECTOR_PORT_GRPC: 4317
  OTEL_COLLECTOR_PORT_HTTP: 4318
  OTEL_COLLECTOR_HOST: opentelemetry-demo-otelcol
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: cumulative
  OTEL_RESOURCE_ATTRIBUTES: service.name=frontendproxy,service.namespace=opentelemetry-demo,service.version=1.12.0



securityContext:
  runAsGroup: 101
  runAsNonRoot: true
  runAsUser: 101
  