apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "opentelemetry-demo-flagd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.tcpService.port }}
      name: {{ .Values.service.tcpService.name }}
      targetPort: {{ .Values.service.tcpService.targetPort }}
    - port: {{ .Values.service.tcpService0.port }}
      name: {{ .Values.service.tcpService0.name }}
      targetPort: {{ .Values.service.tcpService0.targetPort }}
  selector:
    {{- include "opentelemetry-demo-flagd.selectorLabels" . | nindent 4}}
