apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "opentelemetry-demo-recommendationservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Values.service.name }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "opentelemetry-demo-recommendationservice.selectorLabels" . | nindent 4}}
