name: opentelemetry-demo-valkey
replicaCount: 1
revisionHistoryLimit: 10

instance: opentelemetry-demo
part-of: opentelemetry-demo
component: valkey

serviceAccount:
  name: opentelemetry-demo

image :
  repository: valkey/valkey
  tag: '7.2-alpine'
  pullPolicy: IfNotPresent

service:
  port: 6379
  name: tcp-service
  targetPort: 6379

ports:
  containerPort: 6379
  name: service

resources:
  limits:
    memory: 20Mi

env:
  AD_SERVICE_PORT: 8080
  OTEL_SERVICE_NAME: vakey
  OTEL_COLLECTOR_NAME: opentelemetry-demo-otelcol
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: cumulative
  OTEL_EXPORTER_OTLP_ENDPOINT: http://$OTEL_COLLECTOR_NAME:4318
  OTEL_RESOURCE_ATTRIBUTES: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0

securityContext:
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 999
