name: opentelemetry-demo-quoteservice
replicaCount: 1
revisionHistoryLimit: 10

instance: opentelemetry-demo
part-of: opentelemetry-demo
component: quoteservice

serviceAccount:
  name: opentelemetry-demo

image :
  repository: ghcr.io/open-telemetry/demo
  tag: "1.12.0-quoteservice"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  name: tcp-service
  targetPort: 8080

ports:
  containerPort: 8080
  name: service

resources:
  limits:
    memory: 40Mi

env:
  FLAG_HOST: opentelemetry-demo-flagd
  FLAG_PORT: 8013
  OTEL_SERVICE_NAME: quoteservice
  OTEL_COLLECTOR_NAME: opentelemetry-demo-otelcol
  QUOTE_SERVICE_PORT: 8080
  OTEL_PHP_AUTOLOAD_ENABLED: true
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: cumulative
  OTEL_EXPORTER_OTLP_ENDPOINT: http://$(OTEL_COLLECTOR_NAME):4317
  OTEL_RESOURCE_ATTRIBUTES: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0

securityContext:
  runAsGroup: 33
  runAsNonRoot: true
  runAsUser: 33
